// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication.Sample.Db;

namespace WebApplication.Sample.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20181120193520_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("WebApplication.Sample.Db.QbKvpState", b =>
                {
                    b.Property<string>("Ticket");

                    b.Property<string>("Key");

                    b.Property<string>("CurrentStep");

                    b.Property<string>("Value");

                    b.HasKey("Ticket", "Key", "CurrentStep");

                    b.ToTable("QbKvpStates");
                });

            modelBuilder.Entity("WebApplication.Sample.Db.QbTicket", b =>
                {
                    b.Property<string>("Ticket")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Authenticated");

                    b.Property<string>("CurrentStep");

                    b.Property<int>("UserId");

                    b.HasKey("Ticket");

                    b.HasIndex("UserId");

                    b.ToTable("QbTickets");
                });

            modelBuilder.Entity("WebApplication.Sample.Db.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new { Id = 1, Password = "password", UserName = "jsgoupil" }
                    );
                });

            modelBuilder.Entity("WebApplication.Sample.Db.QbTicket", b =>
                {
                    b.HasOne("WebApplication.Sample.Db.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
