namespace QbSync.QbXml.Struct
{
    public enum AssignToObject
    {
        Account,
        ARRefundCreditCard,
        Bill,
        BillPaymentCheck,
        BillPaymentCreditCard,
        BuildAssembly,
        Charge,
        Check,
        Company,
        CreditCardCharge,
        CreditCardCredit,
        CreditMemo,
        Customer,
        Deposit,
        Employee,
        Estimate,
        InventoryAdjustment,
        Invoice,
        Item,
        ItemReceipt,
        JournalEntry,
        OtherName,
        PurchaseOrder,
        ReceivePayment,
        SalesOrder,
        SalesReceipt,
        SalesTaxPaymentCheck,
        Vendor,
        VendorCredit
    }
}